language: java
jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6
before_install:
  - git clone --depth 1 https://github.com/NGDATA/lilyproject.git -b RELEASE_2_0
  - cd lilyproject
  - mvn clean install -DskipTests=true
  - cd ..
  - git clone --depth 1 https://github.com/openplanets/scape-platform-datamodel.git
  - cd scape-platform-datamodel
  - mvn clean install -DskipTests=true
  - cd ..