language: java
jdk:
  - oraclejdk7
  - openjdk7
before_install:
  - git clone --depth 1 https://github.com/openplanets/scape-platform-datamodel.git -b scape-platform-datamodel-0.1.0
  - cd scape-platform-datamodel
  - mvn clean install -DskipTests=true
  - cd ..